plugin-version: ${version}

portstones:
  air:
    cooldown: 600 # in seconds
    warmup: 5 # in seconds
    range: -1 # -1 to disable
  sea:
    cooldown: 1200 # in seconds
    warmup: 5 # in seconds
    range: -1 # -1 to disable
  land:
    cooldown: 1200 # in seconds
    warmup: 5 # in seconds
    range: 1000 # -1 to disable

economy:
  enabled: true
  requireBalance: true

gui:
  titleColor: black
