plugin-version: ${version}

# --- General Travel Rules ---
teleport-rules:
  allow-cross-world-travel: false
  disabled-worlds:
    - "world_the_end"
    - "world_nether"
    - "resource_world"

# --- Portstone Type Settings ---
portstones:
  air:
    cooldown: 600
    warmup: 5
    range: -1
  sea:
    cooldown: 1200
    warmup: 5
    range: -1
  land:
    cooldown: 1200
    warmup: 5
    range: 1000

# --- Economy Settings ---
economy:
  enabled: true
  requireBalance: true

# --- GUI Settings ---
gui:
  fill-item: 'GRAY_STAINED_GLASS_PANE'
  special-items:
    town-spawn:
      enabled: true
      slot: 4
      item: 'COMPASS'
      name: '<gold><b>Home Sweet Home</b></gold>'
      lore:
        - '<gray>Click to teleport to your</gray>'
        - '<gray>town''s spawn point.</gray>'

# --- Effects Settings ---
effects:
  warmup:
    particle: ENCHANT
    count: 10
  sounds:
    warmup-start: 'BLOCK_BEACON_ACTIVATE'
    teleport-success: 'ENTITY_ENDERMAN_TELEPORT'
    teleport-cancel: 'BLOCK_REDSTONE_TORCH_BURNOUT'

# --- BlueMap Integration Settings ---
bluemap-integration:
  icons:
    # URL to a 32x32 png icon for Land ports
    land: "icons/land-icon.png"
    # URL to a 32x32 png icon for Sea ports
    sea: "icons/sea-icon.png"
    # URL to a 32x32 png icon for Air ports
    air: "icons/air-icon.png"

# --- Message Settings ---
messages:
  gui-title: '<black> Teleport from: <white>{source_name}</white></black>'

  teleport-success: '<green>Teleported to <aqua>{destination_name}</aqua>!</green>'
  teleport-warmup: '<yellow>Teleporting in {seconds} seconds. Don''t move!</yellow>'
  teleport-cancelled-move: '<red>Teleport cancelled. You moved.</red>'

  error-on-cooldown: '<red>You are on cooldown for this port type. Time remaining: {time}s</red>'
  error-cant-afford: '<red>You can''t afford the {fee} travel fee!</red>'
  error-stormy-seas: '<red>The seas are too rough! You cannot use sea ports during a storm.</red>'

  warning-no-destinations: '<yellow>No available destinations of this type."</yellow>'

  # Command feedback
  # Generic
  error-command-player-only: '<red>This command can only be run by a player.</red>'
  error-command-not-in-view: '<red>You are not looking at a portstone</red>'
  error-command-invalid-type: '<red>Invalid Portstone type. Use AIR, LAND, or SEA.</red>'
  error-command-already-taken: '<red>That display name is already in use by another portstone.</red>'

  # Help command
  error-command-no-info: '<red>Error: Could not find command information.</red>'
  error-command-no-description: 'No description available.'

  # Edit command
  error-command-not-mayor: '<red>You do not have permission to edit this portstone.</red>'
  error-command-invalid-property: "<red>Unknown property '{property}'.</red>"
  error-command-negative-value: '<red>Fee cannot be negative.</red>'
  error-command-invalid-value: "<red>'{value}' is not a valid number.</red>"
  error-command-invalid-item: "<red>'{value}' is not a valid item.</red>"
  success-command-fee-edited: '<green>Portstone fee updated</green>'
  success-command-name-edited: '<green>"Portstone name updated.</green>'
  success-command-icon-edited: '<green>Portstone icon updated.</green>'
  success-command-status-edited: '<green>Portstone status updated.</green>'

  # Info command
  error-command-invalid-identifier: "<red>No portstone found with identifier: '<white>{identifier}</white>'</red>"

  # List command
  warning-command-none-found: '<yellow>No portstones found matching your criteria.</yellow>'

  # Reload command
  info-command-reload-starting: '<green>Reloading AstradalPorts configuration...</green>'
  success-command-reload-complete: '<green>Reload complete! Took {duration}ms.</green>'

  # Remove command
  success-command-removed: '<green>Portstone removed successfully!</green>'
  success-command-removed-id: '<green>Portstone {id} removed successfully!</green>'
  error-command-invalid-id: '<red>That is not a valid UUID format.</red>'

  # Teleport command
  error-command-not-found: "<red> No portstone named '<white>{destination}</white>' was found.</red>"
  # Success is under teleport-success

  # Version command
  info-command-version: '<gold>AstradalPorts</gold> <gray>version</gray> <aqua>{version}</aqua>'